import type { NextPage } from 'next';
import { css, jsx } from '@emotion/react';
import Image from 'next/image';
import Head from 'next/head';

const divStyle = css`
  background-color: hotpink;
  font-size: 24px;
  border-radius: 4px;
  padding: 32px;
  text-align: center;

  &:hover {
    color: white;
  }
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>MOZUKA</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div css={divStyle}>안녕하세요</div>
      <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
    </div>
  );
};

export default Home;
